In [2]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import r2_score
from sklearn.metrics import classification_report
from sklearn.metrics import precision_score

In [4]:
df = pd.read_csv('/content/IRIS dataset for KNN.csv')
# print(df)

In [5]:
x = df[['SepalLengthCm','SepalWidthCm','PetalLengthCm']].values
y = df['Species'].values
# print(x,y)

In [7]:
# training,testing
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.20,random_state=0)
knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(x_train,y_train)
y_pred = knn.predict(x_test)
# print(y_pred)
# print(y_test)

In [8]:
# Logreg = LogisticRegression()
# # fit the model with data
# Logreg.fit(x_train,y_train)
# # prediction
# y_pred=Logreg.predict(x_test)
# print(y_pred)
# print(y_test)

In [9]:
confussion_metrics=confusion_matrix(y_test,y_pred)
accuracy=accuracy_score(y_test,y_pred)
print("accuracy",accuracy)
# classification_report = classification_report(y_test,y_pred)
# print(classification_report)
precision = precision_score(y_test,y_pred, average='macro')
print("precision",precision)
# r2 = r2_score(y_test,y_pred)
# print(r2)
print("Confusion Metrics :" )
print(confussion_metrics)

accuracy 0.9333333333333333
precision 0.9166666666666666
Confusion Metrics :
[[11  0  0]
 [ 0 11  2]
 [ 0  0  6]]
